### ISSUE TITLE
How to get the batches return value?

### ISSUE THREAD

**Issue by NLP-Peter** [clokep/celery-batches#20] opened 2020-03-21 16:39 UTC
Hi,

I am using the example code to try to get the return value by using get() function. However, it raised an error as blow:
````
Traceback (most recent call last):
  File "/mnt/d/pycharm/smt_simulator/test.py", line 9, in <module>
    process.get()
  File "/usr/local/lib/python3.6/dist-packages/celery/result.py", line 228, in get
    on_message=on_message,
  File "/usr/local/lib/python3.6/dist-packages/celery/backends/base.py", line 571, in wait_for_pending
    no_ack=no_ack,
  File "/usr/local/lib/python3.6/dist-packages/celery/backends/base.py", line 873, in _is_disabled
    raise NotImplementedError(E_NO_BACKEND.strip())
NotImplementedError: No result backend is configured.
Please see the documentation for more information.
```` 
The worker code is:
````
import requests
from urllib.parse import urlparse
from celery_batches import Batches
from celery import Celery

app = Celery('google_streamer',broker='redis://localhost:6379')
app.conf.worker_prefetch_multiplier = 0
wot_api_target = 'https://api.mywot.com/0.4/public_link_json'

@app.task(base=Batches, flush_every=100, flush_interval=10)
def wot_api(requests):
    sig = lambda url: url
    reponses = wot_api_real(
        (sig(*request.args, **request.kwargs) for request in requests)
    )
    # use mark_as_done to manually return response data
    for response, request in zip(reponses, requests):
        app.backend.mark_as_done(request.id, response)

def wot_api_real(urls):
    domains = [urlparse(url).netloc for url in urls]
    response = requests.get(
        wot_api_target,
        params={'hosts': ('/').join(set(domains)) + '/'}
    )
    return [response.json()[domain] for domain in domains]
````
The celery running command is:
`celecy -A tasks worker -l info -B`
The calling code is:
````
from tasks import  wot_api

process = wot_api.delay('http://example.com')
process.get()
````

**Comment by dicato** [comment] 2020-03-24 17:54
Based on the exception you are seeing:

```
NotImplementedError: No result backend is configured.
Please see the documentation for more information.
```

That exception is being generated from Celery. Have you configured Celery to save results? Here are their docs: https://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results

**Comment by clokep** [comment] 2020-03-24 17:57
I should also mention that I'm unsure if results can be returned like this. It isn't really a use-case I've needed before.

The overall task run does *not* return a result (by design) since it doesn't really make sense (at least I've never been able to come up with a reasonable design for this). Handling tasks in a batch and giving each one a result doesn't sound crazy though.

**Comment by clokep** [comment] 2020-11-25 20:35
Closing based on lack of reply from the reporter.

**Closed by clokep** 2020-11-25 20:35 UTC
